name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  material_color_utilities: ^0.11.1
  vm_service: ^14.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/images/logo.png
  uses-material-design: true
