name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.1

# Add regular dependencies here.
dependencies:
  postgres: ^3.5.4
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
